name: CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build-crawl-function:
    uses: ./.github/workflows/build-lambda-function.yaml
    with:
      name: crawl-function
      lambda-function-name: CRAWL_crawl-function
      region: ap-southeast-1
      uploads: |
        functions/crawl-function/config
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      account-id: ${{ secrets.AWS_ACCOUNT_ID }}

  build-raw-accom-function:
    uses: ./.github/workflows/build-lambda-function.yaml
    with:
      name: raw-accom-function
      lambda-function-name: CRAWL_raw-accom-function
      region: ap-southeast-1
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      account-id: ${{ secrets.AWS_ACCOUNT_ID }}
